package com.aigor.app

import androidx.annotation.ColorInt
import androidx.annotation.DrawableRes

object ThemeManager {
    const val PREF_KEY = "app_theme"

    data class UiTheme(
        val id: String,
        val label: String,
        val labelKey: String,
        @ColorInt val screenBg: Int,
        @ColorInt val titleColor: Int,
        @ColorInt val statusColor: Int,
        @ColorInt val messageTextColor: Int,
        @ColorInt val messageHintColor: Int,
        @ColorInt val menuDotsColor: Int,
        @ColorInt val menuTint: Int,
        @ColorInt val sendTint: Int,
        @ColorInt val sendText: Int,
        @ColorInt val userText: Int,
        @ColorInt val botText: Int,
        @ColorInt val typingDots: Int,
        @ColorInt val dialogBg: Int,
        @DrawableRes val userBubble: Int,
        @DrawableRes val botBubble: Int,
        @DrawableRes val inputBg: Int,
        val isLight: Boolean,
        @ColorInt val drawerItemActiveBg: Int,
        @ColorInt val drawerItemInactiveBg: Int,
    )

    val themes = listOf(
        UiTheme(
            id = "light_clean",
            label = "Clar-Blau",
            labelKey = "theme_light_clean",
            screenBg = 0xFFFFFFFF.toInt(),
            titleColor = 0xFF0F172A.toInt(),
            statusColor = 0xFF475569.toInt(),
            messageTextColor = 0xFF0F172A.toInt(),
            messageHintColor = 0xFF64748B.toInt(),
            menuDotsColor = 0xFF334155.toInt(),
            menuTint = 0xFFE2E8F0.toInt(),
            sendTint = 0xFF2563EB.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFF0F172A.toInt(),
            botText = 0xFF0F172A.toInt(),
            typingDots = 0xFF475569.toInt(),
            dialogBg = 0xFFF6F5F4.toInt(),
            userBubble = R.drawable.bg_chat_user_light,
            botBubble = R.drawable.bg_chat_bot_light,
            inputBg = R.drawable.bg_input_chat_light,
            isLight = true,
            drawerItemActiveBg = 0xFFDDE7F3.toInt(),
            drawerItemInactiveBg = 0x00FFFFFF,
        ),
        UiTheme(
            id = "clar_verd",
            label = "Clar-Verd",
            labelKey = "theme_clar_verd",
            screenBg = 0xFFFFFFFF.toInt(),
            titleColor = 0xFF0F172A.toInt(),
            statusColor = 0xFF475569.toInt(),
            messageTextColor = 0xFF0F172A.toInt(),
            messageHintColor = 0xFF64748B.toInt(),
            menuDotsColor = 0xFF334155.toInt(),
            menuTint = 0xFFE2E8F0.toInt(),
            sendTint = 0xFF57E389.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFF0F172A.toInt(),
            botText = 0xFF0F172A.toInt(),
            typingDots = 0xFF475569.toInt(),
            dialogBg = 0xFFF6F5F4.toInt(),
            userBubble = R.drawable.bg_chat_user_light_green,
            botBubble = R.drawable.bg_chat_bot_light,
            inputBg = R.drawable.bg_input_chat_light,
            isLight = true,
            drawerItemActiveBg = 0xFFD7E6D6.toInt(),
            drawerItemInactiveBg = 0x00FFFFFF,
        ),
        UiTheme(
            id = "clar_vermell",
            label = "Clar-Vermell",
            labelKey = "theme_clar_vermell",
            screenBg = 0xFFFFFFFF.toInt(),
            titleColor = 0xFF0F172A.toInt(),
            statusColor = 0xFF475569.toInt(),
            messageTextColor = 0xFF0F172A.toInt(),
            messageHintColor = 0xFF64748B.toInt(),
            menuDotsColor = 0xFF334155.toInt(),
            menuTint = 0xFFE2E8F0.toInt(),
            sendTint = 0xFFFF5C5C.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFF0F172A.toInt(),
            botText = 0xFF0F172A.toInt(),
            typingDots = 0xFF475569.toInt(),
            dialogBg = 0xFFF6F5F4.toInt(),
            userBubble = R.drawable.bg_chat_user_light_red,
            botBubble = R.drawable.bg_chat_bot_light,
            inputBg = R.drawable.bg_input_chat_light,
            isLight = true,
            drawerItemActiveBg = 0xFFF1D7D7.toInt(),
            drawerItemInactiveBg = 0x00FFFFFF,
        ),
        UiTheme(
            id = "dark_blue",
            label = "Dark Blue",
            labelKey = "theme_dark_blue",
            screenBg = 0xFF0B1018.toInt(),
            titleColor = 0xFFF3F4F6.toInt(),
            statusColor = 0xFF7C879A.toInt(),
            messageTextColor = 0xFFF9FAFB.toInt(),
            messageHintColor = 0xFF7C879A.toInt(),
            menuDotsColor = 0xFFF3F4F6.toInt(),
            menuTint = 0xFF0D1C39.toInt(),
            sendTint = 0xFF3584E4.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFFFFFFFF.toInt(),
            botText = 0xFFF9FAFB.toInt(),
            typingDots = 0xFFD1D5DB.toInt(),
            dialogBg = 0xFF111827.toInt(),
            userBubble = R.drawable.bg_chat_user_dark_blue_new,
            botBubble = R.drawable.bg_chat_bot_black,
            inputBg = R.drawable.bg_input_chat,
            isLight = false,
            drawerItemActiveBg = 0xFF58765E.toInt(),
            drawerItemInactiveBg = 0x00273A2B,
        ),
        UiTheme(
            id = "dark_green",
            label = "Dark Green",
            labelKey = "theme_dark_green",
            screenBg = 0xFF0B1018.toInt(),
            titleColor = 0xFFF3F4F6.toInt(),
            statusColor = 0xFF7C879A.toInt(),
            messageTextColor = 0xFFF9FAFB.toInt(),
            messageHintColor = 0xFF7C879A.toInt(),
            menuDotsColor = 0xFFF3F4F6.toInt(),
            menuTint = 0xFF273929.toInt(),
            sendTint = 0xFFB2E4C3.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFF000000.toInt(),
            botText = 0xFFF9FAFB.toInt(),
            typingDots = 0xFFD1D5DB.toInt(),
            dialogBg = 0xFF111827.toInt(),
            userBubble = R.drawable.bg_chat_user_dark_green,
            botBubble = R.drawable.bg_chat_bot_black,
            inputBg = R.drawable.bg_input_chat,
            isLight = false,
            drawerItemActiveBg = 0xFF58765E.toInt(),
            drawerItemInactiveBg = 0x00273A2B,
        ),
        UiTheme(
            id = "dark_red",
            label = "Dark Red",
            labelKey = "theme_dark_red",
            screenBg = 0xFF0B1018.toInt(),
            titleColor = 0xFFF3F4F6.toInt(),
            statusColor = 0xFF7C879A.toInt(),
            messageTextColor = 0xFFF9FAFB.toInt(),
            messageHintColor = 0xFF7C879A.toInt(),
            menuDotsColor = 0xFFF3F4F6.toInt(),
            menuTint = 0x00000000,
            sendTint = 0xFFFF5C5C.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFF000000.toInt(),
            botText = 0xFFF9FAFB.toInt(),
            typingDots = 0xFF9CB9D5.toInt(),
            dialogBg = 0xFF111827.toInt(),
            userBubble = R.drawable.bg_chat_user_dark_red_new,
            botBubble = R.drawable.bg_chat_bot_black,
            inputBg = R.drawable.bg_input_chat,
            isLight = false,
            drawerItemActiveBg = 0xFF58765E.toInt(),
            drawerItemInactiveBg = 0x00273A2B,
        ),
        UiTheme(
            id = "darkred2",
            label = "Dark Red 2",
            labelKey = "theme_darkred2",
            screenBg = 0xFF0B1018.toInt(),
            titleColor = 0xFFF3F4F6.toInt(),
            statusColor = 0xFF7C879A.toInt(),
            messageTextColor = 0xFFF9FAFB.toInt(),
            messageHintColor = 0xFF7C879A.toInt(),
            menuDotsColor = 0xFFF3F4F6.toInt(),
            menuTint = 0x00000000,
            sendTint = 0xFFFF5C5C.toInt(),
            sendText = 0xFFFFFFFF.toInt(),
            userText = 0xFFF9FAFB.toInt(),
            botText = 0xFFF9FAFB.toInt(),
            typingDots = 0xFF9CB9D5.toInt(),
            dialogBg = 0xFF111827.toInt(),
            userBubble = R.drawable.bg_chat_user_ember,
            botBubble = R.drawable.bg_chat_bot_darkred2,
            inputBg = R.drawable.bg_input_chat,
            isLight = false,
            drawerItemActiveBg = 0xFF58765E.toInt(),
            drawerItemInactiveBg = 0x00273A2B,
        )
    )

    fun byId(id: String?): UiTheme = themes.firstOrNull { it.id == id } ?: themes.first()
}
